### ISSUE TITLE
Feedback for v1 messages

### ISSUE THREAD

**Issue by emtay** [FightPandemics/FightPandemics#1599]
Great foundation for messaging feature. Here is consolidated feedback:

1. 
This: 
![image](https://user-images.githubusercontent.com/43509421/95946113-b9ea4a80-0da0-11eb-9cc4-b31dee8370b3.png)

Should look like this: https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17173%3A87887
![image](https://user-images.githubusercontent.com/43509421/95244642-165cd100-07c7-11eb-8c61-0d76888a8569.png)

2. Done!
Avatar missing in message conversation view (JV)
![image](https://user-images.githubusercontent.com/43509421/95245452-fd085480-07c7-11eb-922a-2f76da40919e.png)

3. 
Make User Name link to Profile:
![image](https://user-images.githubusercontent.com/43509421/95946296-1c434b00-0da1-11eb-9f34-7eb5ec33c7d0.png)

4. 

5.

**Comment by rabbi08** [comment]
@emtay @Zaydme 
While testing the feature, I have following observation:
1. If user does not Click on 'View message' after sending the message, below 2 issues have been observed:
    a. the user is not displayed in message section. Refer below GIF, that inbox does not display correct messages/post and other issues occurred due to that (b & c)
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/67168400/96023006-c5308b00-0e1f-11eb-8970-cdcf4f7c57ed.gif)
    
    b.  Wrong user, post and messages are displayed as shown in below screenshot

![image](https://user-images.githubusercontent.com/67168400/96021738-d8425b80-0e1d-11eb-9dc8-8acad9bf4797.png)

     c.  then user is NOT displayed in the 'Message section', as shown in below screenshot 
![image](https://user-images.githubusercontent.com/67168400/96022018-40913d00-0e1e-11eb-8c14-f87fb715289f.png)

2. On the Inbox page, the FP logo is not aligned with  'Messages' pane. Either, can we create separate section for the messages or align it with the logo as in 'HelpBoard' page. Please see below screenshot.
![image](https://user-images.githubusercontent.com/67168400/96020437-058e0a00-0e1c-11eb-94ef-0397295cdfb0.png)

unable to view the message received after clicking on the message (1) icon. (Currently @zayd working on it). Refer below GIF
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/67168400/96020640-54d43a80-0e1c-11eb-9319-fdfadb3e0834.gif)

**Comment by rabbi08** [comment]
@Zaydme 
It looks the online user is having issue, if the user is online it is NOT shown in messages even if I click on 'View message' chat is displayed but when I navigate to other user, the active user is lost. Refer below GIF.
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/67168400/96023980-30c72800-0e21-11eb-8fdf-0260430f6f2d.gif)

**Comment by shrutigupta1981** [comment]
Testing

**Comment by Latha-AP** [comment]
**While the conversation is archived for user1, and if the user2 sends a message to user1 then , that conversation gets removed from the list of archived conversations and is visible to the user1.**
this Scenario is failing through these steps
1.user 1 archived user2
2.user2 messaged
3. user1 Inbox is not showing the wser2's message since it is archived, but notification on top right corner is increased by 1.
4. User 2 has to unarchive manually going into messages settings.



![Screenshot 2020-10-15 105842](https://user-images.githubusercontent.com/72217779/96169331-d092bd80-0ed6-11eb-93b3-3ea56e94b15a.png)
![Screenshot 2020-10-15 110028](https://user-images.githubusercontent.com/72217779/96169344-d2f51780-0ed6-11eb-93a6-46e64e75f64d.png)
![Screenshot 2020-10-15 110128](https://user-images.githubusercontent.com/72217779/96169348-d38dae00-0ed6-11eb-944d-3edc9d3171bd.png)
![Screenshot 2020-10-15 110156](https://user-images.githubusercontent.com/72217779/96169353-d4bedb00-0ed6-11eb-8160-541a55b9690c.png)
![Screenshot 2020-10-15 110320](https://user-images.githubusercontent.com/72217779/96169358-d5577180-0ed6-11eb-87fb-4f3b8edb55d9.png)
![Screenshot 2020-10-15 110418](https://user-images.githubusercontent.com/72217779/96169363-d5f00800-0ed6-11eb-8dd3-436270a2a430.png)
![Screenshot 2020-10-15 110716](https://user-images.githubusercontent.com/72217779/96169365-d6889e80-0ed6-11eb-8cf7-1279cdf98d6a.png)
![Screenshot 2020-10-15 110759](https://user-images.githubusercontent.com/72217779/96169367-d7213500-0ed6-11eb-9406-0d6ef1e732db.png)

**Comment by claudiang1357** [comment]
'error.http.Network' Error is sometimes encountered from Inbox icon in the header (I am in the inbox and then click on Help Board) to Help Board.  This happens on and off.
![Network Error for Inbox icon to Help Board](https://user-images.githubusercontent.com/72559826/96186122-f933ab00-0f08-11eb-9eda-3e1a08df8765.JPG)

**Comment by Zaydme** [comment]
Please allow 5 minutes for the review build to be up to date, then

@rabbi08 
please confirm that these bugs are fixed:
- all from [here](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-708543469)
- all from [here](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-708549000)

@Latha-FP 
please confirm that [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-709491435) was fixed.

@claudiang1357 
please confirm that [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-709591563) was fixed

**Comment by Latha-AP** [comment]
> 
> @Latha-FP
> please confirm that [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-709491435) was **fixed.**

**Bug Fixed**
> 
>

**Comment by Bhavaninalla** [comment]
When i am testing messages using this link  https://www.amazon.com is not open and if i give amazon.com it's perfectly working in inbox messages.
<img width="960" alt="Screenshot 2020-10-15 160616" src="https://user-images.githubusercontent.com/72236992/96195153-def5cf00-0f00-11eb-8e8f-3c5b23e03df6.png">
<img width="960" alt="Screenshot 2020-10-15 160642" src="https://user-images.githubusercontent.com/72236992/96195175-f03edb80-0f00-11eb-86d4-5907682c2f3e.png">
<img width="960" alt="Screenshot 2020-10-15 160727" src="https://user-images.githubusercontent.com/72236992/96195178-f46af900-0f00-11eb-8b7c-69517e2ab4d5.png">

**Comment by Latha-AP** [comment]
**1.User1 sent this link in messages to user 2.** 
https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-708543469
**Now this user1 is blocked/ the site is not opening with this user using this link**
https://featuremessage-modal1457.fightpandemics.xyz/inbox

**2.User2:Receiver couldn't open the link which might be expected
![Github url conversation](https://user-images.githubusercontent.com/72217779/96197549-47e04580-0f07-11eb-88a1-7402aa42e432.png)
![Screenshot 2020-10-15 162318](https://user-images.githubusercontent.com/72217779/96197553-4878dc00-0f07-11eb-8f3c-3249d7a5fe2d.png)
![URL not working](https://user-images.githubusercontent.com/72217779/96197554-4878dc00-0f07-11eb-965f-6de5e391f45b.png)


**This might be the expected behavior due security reasons

**Comment by Zaydme** [comment]
@Latha-FP was this the one fixed or another issues?

**Comment by Latha-AP** [comment]
> @Latha-FP was this the one fixed or another issues?

fixed

**Comment by claudiang1357** [comment]
> 'error.http.Network' Error is sometimes encountered from Inbox icon in the header (I am in the inbox and then click on Help Board) to Help Board. This happens on and off.
> ![Network Error for Inbox icon to Help Board](https://user-images.githubusercontent.com/72559826/96186122-f933ab00-0f08-11eb-9eda-3e1a08df8765.JPG)

**Comment by claudiang1357** [comment]
Today (10/16), tried again, the same error is still existed

**Comment by Bhavaninalla** [comment]
I swipe down to see the message history again and again in the chat box, at the end it is redirecting to the home page.
Layout on mobile : Android
![WhatsApp Image 2020-10-16 at 8 07 26 AM (1)](https://user-images.githubusercontent.com/72236992/96280280-a13e8800-0f8c-11eb-85dd-620ba27651f1.jpeg)
![WhatsApp Image 2020-10-16 at 8 07 26 AM (2)](https://user-images.githubusercontent.com/72236992/96280413-caf7af00-0f8c-11eb-8291-040f01c49cde.jpeg)
![WhatsApp Image 2020-10-16 at 8 07 26 AM](https://user-images.githubusercontent.com/72236992/96280311-ab608680-0f8c-11eb-89e6-562c6ded16b4.jpeg)

**Comment by rabbi08** [comment]
@Zaydme 
- Verified the issue -> if user click 'Done' after posting the message, and navigate to Inbox, the message is displayed as expected in the Inbox.
- Verified that 'Messages' pane is aligned with FP logo -PASS
- Verified that if user click on the message icon to see the messages is working fine: PASS


Another issues observed:
1. Unable to send the message after EDIT. Refer below GIF
![ezgif com-gif-maker (10)](https://user-images.githubusercontent.com/67168400/96280866-8416b300-0fa6-11eb-8a28-84698e40382f.gif)

2. Unable to send emoji in the message. Refer below screenshot.
![image](https://user-images.githubusercontent.com/67168400/96280927-a01a5480-0fa6-11eb-9621-0de4f2306d8a.png)

3. 'Load more' text is displayed even when there is no more messages to be displayed. Also, can we change the 'load more' as 'Load more.. ' Refer below GIF
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/67168400/96280567-19fe0e00-0fa6-11eb-9bde-dd84ed73099e.gif)

4. While navigating from Inbox to Help Board, I dont see error BUT the help Board take time to load. Refer below GIF. This doesn't take time in general.
![ezgif com-gif-maker (11)](https://user-images.githubusercontent.com/67168400/96281624-947b5d80-0fa7-11eb-854c-b96ec7876624.gif)

Thanks

**Comment by rabbi08** [comment]
@Zaydme 
While testing on mobile (iphone 11 pro max). following issues have been observed, thanks:

- All the messages are displayed overlapped to show on the screen. refer below GIF and screenshot.
![IMG_3391](https://user-images.githubusercontent.com/67168400/96283138-bfff4780-0fa9-11eb-845b-e1f233c69616.PNG)

![ezgif com-gif-maker (12)](https://user-images.githubusercontent.com/67168400/96283104-b37aef00-0fa9-11eb-8fbd-866d2b07f56a.gif)

- White space exist at the end of the in the end of the message pane.(Both mobile and desktop) refer below screenshot.
![Screenshot 2020-10-16 at 12 12 25 PM](https://user-images.githubusercontent.com/67168400/96283159-c5f52880-0fa9-11eb-9d72-931ebb673da5.png)

![image](https://user-images.githubusercontent.com/67168400/96282982-757dcb00-0fa9-11eb-8d98-844493312a10.png)

**Comment by nivetheatha** [comment]
Tested on Android Mobile
Last sent Message has no Timestamp.It would be great if it shows as Just now.
![Screenshot_20201016-152859_Chrome](https://user-images.githubusercontent.com/41587211/96301194-d1a21880-0fc4-11eb-9131-5c47347b5843.jpg)

**Comment by nivetheatha** [comment]
Tested on Android mobile.
If the post has long title and user tries to send a message then the heading is not fit into screen.
![Screenshot_20201015-151434_Chrome (1)](https://user-images.githubusercontent.com/41587211/96301892-df0bd280-0fc5-11eb-94df-faec949b8423.jpg)

**Comment by nivetheatha** [comment]
Tested in Android Mobile
Not able to update Edited chat.
![Screenshot_20201016-103724_Chrome](https://user-images.githubusercontent.com/41587211/96302263-7ffa8d80-0fc6-11eb-9681-dd4d95e59821.jpg)

**Comment by nivetheatha** [comment]
Tested on Android mobile
Inbox--->Message Settings-->Blocked accounts/Archieved Conversations --->Not able to choose Inbox from the Menu
![GIF-201016_155506](https://user-images.githubusercontent.com/41587211/96303298-2c893f00-0fc8-11eb-9472-ab3686151dfe.gif)

**Comment by nivetheatha** [comment]
Tested on Android Mobile
Inbox-->Read Message--->Select Inbox from menu-->Blank page
![GIF-201016_160055](https://user-images.githubusercontent.com/41587211/96303834-15971c80-0fc9-11eb-8ce8-d5ad8616a7f6.gif)

**Comment by nivetheatha** [comment]
Tested on Android Mobile 
Inbox-->Read Message-->click on archive the messages-->Blank page
If we  refresh moved to Home page.
![GIF-201016_163101](https://user-images.githubusercontent.com/41587211/96306493-c3a4c580-0fcd-11eb-8622-279470eac94d.gif)

**Comment by Zaydme** [comment]
Thank you for testing! please confirm the below

@Bhavaninalla 
- [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-709636981) was fixed.

@rabbi08 
- the bugs 1,3 [here](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710147215) are fixed.
   - for 2, we don't support text to emojis conversion yet,should we? (this will require an external library, i found [react-emojione](https://www.npmjs.com/package/react-emojione) but it's 17.5MB!!)
   - 4 was not a bug
- the white space bug [here](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710166351) was fixed
   - for the IOS layout we are still waiting on a FE dev with access to an IOS device to debug it.

@nivetheatha 
- [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710496756) was fixed.
- [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710504050) was fixed.
- [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710520752) was fixed.
- [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710531126) was fixed.
- [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710584899) was fixed.

**Comment by nivetheatha** [comment]
> Tested on Android mobile.
> If the post has long title and user tries to send a message then the heading is not fit into screen.
> ![Screenshot_20201015-151434_Chrome (1)](https://user-images.githubusercontent.com/41587211/96301892-df0bd280-0fc5-11eb-94df-faec949b8423.jpg)

Woks as expected 
![Screenshot_20201016-220903_Chrome](https://user-images.githubusercontent.com/41587211/96326199-9c192180-0ffc-11eb-9f0d-e3112fa78da9.jpg)

**Comment by nivetheatha** [comment]
> Tested in Android Mobile
> Not able to update Edited chat.
> ![Screenshot_20201016-103724_Chrome](https://user-images.githubusercontent.com/41587211/96302263-7ffa8d80-0fc6-11eb-9681-dd4d95e59821.jpg)

Able to update edited test.

**Comment by nivetheatha** [comment]
> Tested on Android mobile
> Inbox--->Message Settings-->Blocked accounts/Archieved Conversations --->Not able to choose Inbox from the Menu
> ![GIF-201016_155506](https://user-images.githubusercontent.com/41587211/96303298-2c893f00-0fc8-11eb-9472-ab3686151dfe.gif)

Able to select inbox now.

**Comment by nivetheatha** [comment]
> Tested on Android Mobile
> Inbox-->Read Message--->Select Inbox from menu-->Blank page
> ![GIF-201016_160055](https://user-images.githubusercontent.com/41587211/96303834-15971c80-0fc9-11eb-8ce8-d5ad8616a7f6.gif)

Inbox is shown as expected.

**Comment by nivetheatha** [comment]
> Tested on Android Mobile
> Inbox-->Read Message-->click on archive the messages-->Blank page
> If we refresh moved to Home page.
> ![GIF-201016_163101](https://user-images.githubusercontent.com/41587211/96306493-c3a4c580-0fcd-11eb-8622-279470eac94d.gif)

Works as expected now.

**Comment by rabbi08** [comment]
@Zaydme 
- I am able to edit the message successfully but the 'edited' text is displayed on the top of the screen not with the timestamp of that message. Please refer below screenshot. Can we display it along with the timestamp, below the message.
![image](https://user-images.githubusercontent.com/67168400/96328176-038b9d00-100e-11eb-884a-2570be5195dd.jpeg)

- On mobile the number of messages displayed is awkward design. It will look more impressive if we can display like "Inbox(2)" or Inbox^2

Please see this screenshot 
![image](https://user-images.githubusercontent.com/67168400/96328068-384b2480-100d-11eb-9a8d-c24db954103a.png)

- while verifying the white screen issues - now unable to see or scroll or access the last user in my inbox.
Refer below gif 

![image](https://user-images.githubusercontent.com/67168400/96328155-d9d27600-100d-11eb-92f2-2502a5367690.gif)


Also we should allow user to send emoji as they are the part of messages in today's world.

**Comment by Latha-AP** [comment]
ISsue with Profile name Edit
1. user edited his name by going into profile.
2.In message box, it is not reflected.

I refreshed the page, I waited for long time.

https://fightpandemics.slack.com/files/U01B3L0AY15/F01D5MMAAM7/fightpandemics_-_google_chrome_2020-10-16_19-13-11_trim.mp4

**Comment by shrutigupta1981** [comment]
Windows OS/ Chrome Browser/ Message Send to an Individual

Issue: Not able to send message again after edit done. Was not able to scroll or Zoom in too

https://files.slack.com/files-pri/T010BHVS3EF-F01DEE3Q6E4/buttonsnotaccessibleandsendingcantbedone.png

**Comment by Zaydme** [comment]
please confirm:
@Latha-FP [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710745824) was fixed
@shrutigupta1981 [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710756591) was fixed

**Comment by Bhavaninalla** [comment]
All the pages staying in the same page after refreshing the pages, only messages page redirects to home page after refreshing.
![WhatsApp Image 2020-10-16 at 8 07 26 AM](https://user-images.githubusercontent.com/72236992/96349635-a7ecfe00-1065-11eb-833c-1dc1edef66a3.jpeg)
![WhatsApp Image 2020-10-16 at 8 07 26 AM (1)](https://user-images.githubusercontent.com/72236992/96349634-a7ecfe00-1065-11eb-97ff-4dd83cf20dc3.jpeg)
![WhatsApp Image 2020-10-16 at 8 07 26 AM (2)](https://user-images.githubusercontent.com/72236992/96349632-a7546780-1065-11eb-8e62-bc607394490e.jpeg)

**Comment by Zaydme** [comment]
@Bhavaninalla a fix has been pushed, please allow few minutes for the review build to be up to date

**Comment by Latha-FP** [comment]
Android Device: Input box couldn't handle the emoji's
![mobile -inputbox -emoji gif](https://user-images.githubusercontent.com/72217779/96355937-a68af800-109c-11eb-9930-b999a060a7da.gif)

**Comment by Latha-FP** [comment]
1. user1 has Gmail account.
2. he signed up/ logged in to fight pandemics with that gamil account.
3. he posted some posts, he messaged on some posts.
4. Now, He deleted the Gmail account permanently. 
5. now someother user is sending messages to this user1, which are reaching as usual.

May be , some back ground checkup might be needed if something happened to the mail id associated with the Fightpandemics. and push some message like 
1."user does not exist  or 
 2.User is no longer associated with FP. or 
3.Send some notification to the user1 saying "your email id is not valid , please update."
  for incomplete profiles like this.

![WhatsApp Image 2020-10-17 at 6 13 26 PM](https://user-images.githubusercontent.com/72217779/96362918-b418a000-10e5-11eb-88a1-88cc29c473b6.jpeg)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/72217779/96362947-e6c29880-10e5-11eb-9950-8355b0a8e5af.gif)

**Comment by Latha-FP** [comment]
> ISsue with Profile name Edit
> 
> 1. user edited his name by going into profile.
>    2.In message box, it is not reflected.
> 
> I refreshed the page, I waited for long time.
> 
> https://fightpandemics.slack.com/files/U01B3L0AY15/F01D5MMAAM7/fightpandemics_-_google_chrome_2020-10-16_19-13-11_trim.mp4

Now We could't see Pen symbol to edit profile/account information
![no pen symbol to edit profile](https://user-images.githubusercontent.com/72217779/96363621-63f00c80-10ea-11eb-8280-3ad9178add8d.png)

**Comment by Bhavaninalla** [comment]
Next line button as working as send button.so i couldn't make a text message on the next line.
![ezgif-6-89a7afcff2a9](https://user-images.githubusercontent.com/72236992/96385879-99791200-114b-11eb-9a29-eba3c9993479.gif)

**Comment by Bhavaninalla** [comment]
Tested on Android Mobile
After I click the message request and I saw the message , but I am not able to view/click  the accept ,ignore buttons .
![ezgif-6-a7ed0fb9c0b8](https://user-images.githubusercontent.com/72236992/96406928-36ac6880-1195-11eb-9e00-d7121647eecd.gif)

**Comment by Latha-AP** [comment]
Direct message on post: testing **View message** vs **Done**
1. View message is  navigating to message box
2. After clicking Done, If we need to give another message on the same post, the **input box is not clearing the previous input.**.Same Behavior observed in mobile too.
3. **In message box, the messages are  showing repeatedly if we are adding new message(since the since the input box has previous ones .**

![DMview message vs done ](https://user-images.githubusercontent.com/72217779/96405777-e16f5780-1192-11eb-9c6a-c05b66454812.png)
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/72217779/96407528-6f007680-1196-11eb-8b13-2eaa79889156.gif)

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/72217779/96418154-32894680-11a7-11eb-8fb1-0e76364b3771.gif)

**Comment by Latha-AP** [comment]
If we change mobile orientation(Vertical to **Horizontal)** ,**We couldn't see Archive and Delete options along with some of the earlier messages**

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/72217779/96414165-9741a280-11a1-11eb-87ba-32181c0cb160.gif)

**Comment by Latha-AP** [comment]
If we change mobile orientation(Vertical to **Horizontal**) ,We couldn't see what we are typing in inbox until we send the message.

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/72217779/96416623-17b5d280-11a5-11eb-8699-4d3da46f2aa5.gif)

**Comment by Bhavaninalla** [comment]
Create two users, user 1 and user 2
1: Open two login window from the same browser ( two tabs)
2: Using the first login window: login as user 1
3: In the second login window: login as user 2
In this case user 1 create a individual post and user 2 create another post and user 2 access user1 post 
![ezgif-7-402287aeb6a2](https://user-images.githubusercontent.com/72236992/96494923-e4eaf900-11fb-11eb-9ce1-58863fcdbdcc.gif)

**Comment by rabbi08** [comment]
> Create two users, user 1 and user 2
> 1: Open two login window from the same browser ( two tabs)
> 2: Using the first login window: login as user 1
> 3: In the second login window: login as user 2
> In this case user 1 create a individual post and user 2 create another post and user 2 access user1 post
> ![ezgif-7-402287aeb6a2](https://user-images.githubusercontent.com/72236992/96494923-e4eaf900-11fb-11eb-9ce1-58863fcdbdcc.gif)

Please note this might be related to the session of the user1, in same browser, you are keeping the same session, to test multiple users, preferably use different browser to keep different sessions. So, it will be great if you can retest the same scenario and update. Thanks

**Comment by Zaydme** [comment]
Please wait few minutes for the review build to update and confirm this:
@Bhavaninalla 
[this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-711424148) was fixed.
@Latha-FP 
[this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-711625546) was fixed.
[this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-711752025) was somewhat fixed.

**Comment by Bhavaninalla** [comment]
@rabbi08 
     
   I tested different browsers with different users, so user 1 can’t access user 2 post.In this scenario it’s working fine.

**Comment by emtay** [comment]
Hi QA team, we're hoping to get some support on mobile FE. I'll post here when progress has been made.

Thanks for all the finds and thank you @Zaydme  for ALLLLL the amazing fixes!!

**Comment by rabbi08** [comment]
@zayd, 
On Desktop: Following issues with scrolling while more users and long chats exist. Please see below GIF.
- The scroll is not working, I used arrow key after selecting a user/chat
- The typing textbox is move in the top of the screen and blank space on the page.
![ezgif com-gif-maker (23)](https://user-images.githubusercontent.com/67168400/96775299-59b56300-13b5-11eb-8baf-cfc7db933a28.gif)

**Comment by shrutigupta1981** [comment]
> Windows OS/ Chrome Browser/ Message Send to an Individual
> 
> Issue: Not able to send a message again after edit is done. Was not able to scroll or Zoom in too
> 
> https://files.slack.com/files-pri/T010BHVS3EF-F01DEE3Q6E4/buttonsnotaccessibleandsendingcantbedone.png

It's still now working. I am able to scroll up and down but by default, it still showing as same. my screen size details- 14.2* 8

![image](https://user-images.githubusercontent.com/72843352/96788549-87e07600-13a8-11eb-841d-2dd4b9edee9e.png)

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/96789447-0db0f100-13aa-11eb-9559-baf9886a6a0b.png)
 
Button behavior: Text- Try Again to be shown white only on click mode

**Comment by shrutigupta1981** [comment]
> please confirm:
> @Latha-FP [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710745824) was fixed
> @shrutigupta1981 [this bug](https://github.com/FightPandemics/FightPandemics/issues/1599#issuecomment-710756591) was fixed
 @Latha-FP I am able to scroll but buttons still not visible,by default. My screen size: 14.2* 8

**Comment by shrutigupta1981** [comment]
Conversation spelling to be corrected

![image](https://user-images.githubusercontent.com/72843352/96793327-00e3cb80-13b1-11eb-945e-1e8eebab6ff7.png)

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/96798207-3f7b8500-13b5-11eb-8557-0128902827fe.png)

Send button label to be in bold as  followed same in Post and Next Buttons

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/96801927-97b68500-13bd-11eb-8ff3-c7f9bf2e836c.png)
   
View Message button text size is very small and it needs to be bold

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/96802665-237ce100-13bf-11eb-9291-bdc733717141.png)
 Pls see the UX of the Send button when clicked. The progress bar or activity control shown as white just before send confirmation message.

**Comment by Bhavaninalla** [comment]
> Next line button as working as send button.so i couldn't make a text message on the next line.
> ![ezgif-6-89a7afcff2a9](https://user-images.githubusercontent.com/72236992/96385879-99791200-114b-11eb-9a29-eba3c9993479.gif)
fixed

**Comment by Bhavaninalla** [comment]
click messages inbox
select user and sending messages to user and not able to see the sending message immediately
![ezgif-2-aa5390adb4e8](https://user-images.githubusercontent.com/72236992/96956244-784a5580-14ac-11eb-97e7-0a3759a882f9.gif)

**Comment by shrutigupta1981** [comment]
Query related to a Scenario: I created a post and left a comment on it. I received a comment from another user saying interest. Now is it possible to reply to the same person through comment? Are we supporting thread kind of thing to maintain a chain of comments for now? No right?Rajbir Kaur  1 day ago
@Shruti Gupta please add your observation related to private message in PR#1599
https://files.slack.com/files-pri/T010BHVS3EF-F01D3A27GLT/image.png

**Comment by Zaydme** [comment]
> Query related to a Scenario: I created a post and left a comment on it. I received a comment from another user saying interest. Now is it possible to reply to the same person through comment? Are we supporting thread kind of thing to maintain a chain of comments for now? 

@shrutigupta1981 No, unfortunately we don't support replying to comments. But you will be able to click on the user's name to go to their profile, from there you can click on the message icon to start a private conversation with them.

**Comment by shrutigupta1981** [comment]
Ok. I put it here as an Observation because was told to do so

**Comment by shrutigupta1981** [comment]
![image](https://user-images.githubusercontent.com/72843352/97063968-bc466480-1557-11eb-8d11-72f7aaf2ad4f.png)
 buttons shape when I click on delete option given into Comment section

**Comment by nivetheatha** [comment]
Tested on Android mobile 
When we open keypad in messenger. We are not able to see last message and not able to scroll down to last message as well.
![GIF-201023_212340](https://user-images.githubusercontent.com/41587211/97064938-e0b23900-1577-11eb-8bed-fb42ee36c665.gif)

**Comment by shrutigupta1981** [comment]
C to be in Caps and Close button text -> Bold
I think message not sent seems to be more appropriate than not successfully sent
its not sent at all so successfully here seems odd
![image (2)](https://user-images.githubusercontent.com/72843352/97794312-5be99f80-1bb5-11eb-9780-39361114972c.png)

**Comment by shrutigupta1981** [comment]
Issue: Message button shown when clicking on Comment. It should have been shown besides Comment?
[MessagebuttonshownonCommentClickoncePeopletabisaccessedafterperformingsearchwithkeywordKhushi (1).zip](https://github.com/FightPandemics/FightPandemics/files/5485084/MessagebuttonshownonCommentClickoncePeopletabisaccessedafterperformingsearchwithkeywordKhushi.1.zip)

**Comment by shrutigupta1981** [comment]
![Orgsearchresult_Messagebuttonclicked](https://user-images.githubusercontent.com/72843352/98061497-d6f2c600-1e00-11eb-81b4-48762226721e.png)
![image (4)](https://user-images.githubusercontent.com/72843352/98061501-d78b5c80-1e00-11eb-8d76-80df6b81b270.png)
![image (4)](https://user-images.githubusercontent.com/72843352/98061510-d9edb680-1e00-11eb-8743-4b17f2c5699b.png)
![Orgsearchresult_Messagebuttonclicked](https://user-images.githubusercontent.com/72843352/98061512-da864d00-1e00-11eb-8df6-11f96d6acfc4.png)
Above shows Org has send email button when searched but When profile viewed of individual , message button there.......difference between Org/Individual why? Emily Taylor:palm_tree:  1 day ago
@Shruti Gupta we will be updating both org and indiv profiles soon so will update these two email icons.

**Comment by Zaydme** [comment]
Please log all the new issues in this new ticked https://github.com/FightPandemics/FightPandemics/issues/1865.
Thank you!
